name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  DRY_RUN: ${{ github.ref != 'refs/heads/main' }}
  DOCKER_BUILDKIT: 1
  USER_NAME: ubuntu
  TEST_IMAGE: renovate/buildpack-test

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    strategy:
      matrix:
        tag:
          [
            dotnet,
            erlang,
            golang,
            java,
            helm,
            nix,
            node,
            php,
            powershell,
            python,
            ruby,
            rust,
            swift,
            latest,
          ]

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - uses: sigstore/cosign-installer@536b37ec5d5b543420bdfd9b744c5965bd4d8730 # tag=v2.3.0

      - name: Init
        run: |
          echo "CACHE_WEEK=$(date +%U)" >> $GITHUB_ENV

      - name: Docker registry login
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: build
        run: docker build -t ${{ env.TEST_IMAGE }} --build-arg USER_NAME .

      - name: test
        run: docker build --build-arg IMAGE=${{ env.TEST_IMAGE }} ./test/${{ matrix.tag }}

      - name: Build and Publish
        if: ${{ matrix.tag == 'latest' }}
        uses: renovatebot/internal-tools@5378c3be65640c186fbafb834a25a205bded4c23 # tag=v1.13.0
        with:
          command: docker-builder
          build-args: USER_NAME,CACHE_WEEK
          last-only: true
          major-minor: false
          dry-run: ${{ env.DRY_RUN }}
