name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  DRY_RUN: ${{ github.ref != 'refs/heads/main' }}
  DOCKER_BUILDKIT: 1
  USER_NAME: ubuntu

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    strategy:
      matrix:
        tag:
          [
            dotnet,
            erlang,
            golang,
            java,
            helm,
            nix,
            node,
            php,
            powershell,
            python,
            ruby,
            rust,
            swift,
            latest,
          ]

    env:
      TARGET: ${{ matrix.tag }}
      TEST_IMAGE: renovate/buildpack-test:${{ matrix.tag }}

    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2.3.5

      - name: Init
        run: |
          echo "CACHE_WEEK=$(date +%U)" >> $GITHUB_ENV

      - name: Docker registry login
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: build
        run: docker build -t ${{ env.TEST_IMAGE }} --build-arg TARGET --build-arg USER_NAME .

      - name: test
        run: docker build --build-arg IMAGE=${{ env.TEST_IMAGE }} ./test/${{ matrix.tag }}

      - name: Build and Publish
        uses: renovatebot/internal-tools@51f6522544e9d8368e9e223dd2948c1eb32db903 # renovate: tag=v1.8.14
        with:
          command: docker-builder
          build-args: TARGET,USER_NAME
          last-only: true
          tag-suffix: ${{ env.TARGET }}
          major-minor: false
          dry-run: ${{ env.DRY_RUN }}


  distro:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    strategy:
      matrix:
        distro:
          [
            bionic,
          ]

    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2.3.5

      - name: build
        run: docker build --build-arg USER_NAME -f test/Dockerfile.${{ matrix.distro }} .
